### ISSUE TITLE
Read configuration from `pyproject.toml` file

### ISSUE THREAD

**Issue by McCache** [McCache/McCache-for-Python#8]
If a `pyproject.toml` exist, we should read `McCache` configuration from it.

Our section shall be `[tool.mccache]`.
All properties are to be in lowercase.

```
[tool.mccache]
ttl = 900
mtu = 1472
```

Properties read from `pyproject.toml` only over-writes the default `McCache` configuration but  does not  over-write the configuration set in the environment variable.

**Comment by McCache** [comment]
Pending testing.

**Comment by elau1004** [comment]
Implemented.
